### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by tmrobert8** [openhab/org.openhab.binding.zwave#1197] opened 2019-07-09 12:03 UTC
Very minor - but if you are making any changes, you might want to fix this:

```Status: OFFLINE - COMMUNICATION_ERROR Serial Error: Port {0} is in use```

Notice the "{0}" in the error message..

**Comment by lolodomo** [comment] 2019-07-25 07:00
I will propose a fix.

**Comment by lolodomo** [comment] 2019-07-25 07:14
It is a duplicate of #1014.
Can be closed.

**Closed** 2019-07-25 07:20 UTC
Labels: duplicate
