### ISSUE TITLE
UID must have at least 2 segments.

### ISSUE THREAD

**Issue by rkoshak** [openhab/org.openhab.binding.zwave#1249] opened 2019-10-16 15:50 UTC
* OH2 Version: 2.5 SNAPSHOT #1723 and later
* Binding Version (if SNAPSHOT, provide compile time as found on the filename in the console): 

If the problem is associated with a device, please provide the following -: 2.5.0.201910150544 (I've updated OH once since the error started showing up.

A full discussion can be found at https://community.openhab.org/t/zwave-openhab-2-5-0-build-1723-exception-during-startup/83565.

Since build 1723, maybe one or two builds before that as I don't update every day, I've been seeing the following exception in the logs during startup followed by a set of warnings:

```
2019-10-14 07:58:16.519 [ERROR] [ig.xml.osgi.XmlDocumentBundleTracker] - Could not send adding finished event for the module 'org.openhab.binding.zwave'!
java.lang.IllegalArgumentException: UID must have at least 2 segments.
        at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:70) ~[133:org.openhab.core:2.5.0.201910140525]
        at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:49) ~[133:org.openhab.core:2.5.0.201910140525]
        at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:48) ~[?:?]
        at org.eclipse.smarthome.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:40) ~[?:?]
        at org.eclipse.smarthome.core.thing.xml.internal.ChannelXmlResult.toChannelDefinition(ChannelXmlResult.java:135) ~[?:?]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toChannelDefinitions(ThingTypeXmlResult.java:94) ~[?:?]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.getBuilder(ThingTypeXmlResult.java:145) ~[?:?]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toThingType(ThingTypeXmlResult.java:153) ~[?:?]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlProvider.addingFinished(ThingTypeXmlProvider.java:147) ~[?:?]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.addingFinished(XmlDocumentBundleTracker.java:265) [142:org.openhab.core.config.xml:2.5.0.201910140543]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.parseDocuments(XmlDocumentBundleTracker.java:424) [142:org.openhab.core.config.xml:2.5.0.201910140543]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.processBundle(XmlDocumentBundleTracker.java:398) [142:org.openhab.core.config.xml:2.5.0.201910140543]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.access$6(XmlDocumentBundleTracker.java:393) [142:org.openhab.core.config.xml:2.5.0.201910140543]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$2.run(XmlDocumentBundleTracker.java:363) [142:org.openhab.core.config.xml:2.5.0.201910140543]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
...
2019-10-14 07:58:21.502 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 5: Device discovery could not resolve to a thingType! 0138:0001:0002::0.5
2019-10-14 07:58:21.507 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 10: Device discovery could not resolve to a thingType! 0138:0001:0002::0.5
2019-10-14 07:58:21.517 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 13: Device discovery could not resolve to a thingType! 0090:0001:0001::3.37
2019-10-14 07:58:21.524 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 12: Device discovery could not resolve to a thingType! 0090:0001:0001::3.37
2019-10-14 07:58:21.607 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 9: Device discovery could not resolve to a thingType! 0138:0001:0002::0.5
```

The nodes that have the warnings are all battery powered devices (Zcombo smoke/CO alarms and Kwickset 910 deadbolts)  but others have reported mains powered devices in their warnings.  Mark Hilbrush reports the exception with just the serial controller and no other devices.

The following is a full debug level log of the startup sequence from the zwave binding. (NOTE: the original exception above comes from the XmlDocumentBundleTracker so is not included in the binding logs.) I notice that during this restart of OH, the list of nodes with the warning is different which might be another clue.

[zwave.log](https://github.com/openhab/org.openhab.binding.zwave/files/3735211/zwave.log)

**Comment by mhilbush** [comment] 2019-10-16 16:03
Adding another datapoint...

With the zwave binding installed, and no zwave things (including no serial controller thing), and some additional debugging turned on, I see this when the binding starts.

```
2019-10-16 12:00:05.865 [DEBUG] [core.thing.internal.ThingManagerImpl] - Thing handler factory 'ZWaveHandlerFactory' added
2019-10-16 12:00:05.869 [TRACE] [ig.xml.osgi.XmlDocumentBundleTracker] - Finished loading bundles with /ESH-INF/config/
2019-10-16 12:00:05.870 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/binding/binding.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:05.871 [TRACE] [ig.xml.osgi.XmlDocumentBundleTracker] - Create an empty XmlDocumentProvider for the module 'org.openhab.binding.zwave'.
2019-10-16 12:00:05.871 [TRACE] [ig.xml.osgi.XmlDocumentBundleTracker] - Finished loading bundles with /ESH-INF/binding/
2019-10-16 12:00:05.876 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/telldus/tzwp100_0_0.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:05.877 [TRACE] [ig.xml.osgi.XmlDocumentBundleTracker] - Create an empty XmlDocumentProvider for the module 'org.openhab.binding.zwave'.
2019-10-16 12:00:05.877 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/permundo/psc234zw_0_0.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:05.877 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/danfoss/lcz251_0_0.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:05.878 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/danfoss/dthermz5_0_0.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:05.879 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/dlink/dchz120_0_0.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:05.880 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/zwaveme/kfob_0_0.xml' in module 'org.openhab.binding.zwave'...

[snip lots of XML file reads]

2019-10-16 12:00:06.717 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/vision/zd2105_0_0.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:06.717 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/vision/zd2201_0_0.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:06.718 [DEBUG] [ig.xml.osgi.XmlDocumentBundleTracker] - Reading the XML document '/ESH-INF/thing/vision/pid15903_0_0.xml' in module 'org.openhab.binding.zwave'...
2019-10-16 12:00:06.732 [ERROR] [ig.xml.osgi.XmlDocumentBundleTracker] - Could not send adding finished event for the module 'org.openhab.binding.zwave'!
java.lang.IllegalArgumentException: UID must have at least 2 segments.
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:70) ~[133:org.openhab.core:2.5.0.201910140525]
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:49) ~[133:org.openhab.core:2.5.0.201910140525]
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:48) ~[?:?]
	at org.eclipse.smarthome.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:40) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ChannelXmlResult.toChannelDefinition(ChannelXmlResult.java:135) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toChannelDefinitions(ThingTypeXmlResult.java:94) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.getBuilder(ThingTypeXmlResult.java:145) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toThingType(ThingTypeXmlResult.java:153) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlProvider.addingFinished(ThingTypeXmlProvider.java:147) ~[?:?]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.addingFinished(XmlDocumentBundleTracker.java:265) [142:org.openhab.core.config.xml:2.5.0.201910140543]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.parseDocuments(XmlDocumentBundleTracker.java:424) [142:org.openhab.core.config.xml:2.5.0.201910140543]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.processBundle(XmlDocumentBundleTracker.java:398) [142:org.openhab.core.config.xml:2.5.0.201910140543]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.access$6(XmlDocumentBundleTracker.java:393) [142:org.openhab.core.config.xml:2.5.0.201910140543]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$2.run(XmlDocumentBundleTracker.java:363) [142:org.openhab.core.config.xml:2.5.0.201910140543]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-10-16 12:00:06.736 [TRACE] [ig.xml.osgi.XmlDocumentBundleTracker] - Finished loading bundles with /ESH-INF/thing/

```

**Comment by cdjackson** [comment] 2019-10-16 16:18
I don’t think this helps, other than to confirm my thinking that it’s not related to the battery devices. I hoped that the error might have been in the last file listed before the exception, but that looks ok. I’ve searched through the thing type specifiers in the last database update, and they all look ok. Unfortunately the previous one is a huge database update and it’s not easy to search the diff.

Can someone narrow down when this started a bit more? There have been a lot of database updates recently…

My guess is that this might be caused by some thing file not having a thing-type specified eg thing-type id=“"

That’s a guess though at the moment.

**Comment by mhilbush** [comment] 2019-10-16 16:24
That last file that was logged, the vision pid15093, was the 996th file that was loaded. So, if there are "about" 1000 thing types, then this is one of the last (or maybe the last) to be loaded. Wondering of the error could be happening after all the files have finished loading?

**Comment by mhilbush** [comment] 2019-10-16 16:27
Any chance that the "registerHandlerLock" PR might've caused this? It was committed to openhab-core on Oct 6. It had something to do with thing type migration.

**Comment by cdjackson** [comment] 2019-10-16 16:30
I’m not sure what that actually did so I can’t really comment. Can you reference the PR as I can’t immediately see one with this title.

**Comment by mhilbush** [comment] 2019-10-16 16:32
Here it is.
https://github.com/openhab/openhab-core/pull/1060

**Comment by cdjackson** [comment] 2019-10-16 16:36
Thanks.

Is everyone with this issue using the latest core? Is anyone with this issue running the latest binding on (say) 2.5M3 or something older than the last week or two?

**Comment by openhab-5iver** [comment] 2019-10-16 16:38
Nobody has tested the latest binding on an older OH build to confirm this is a binding issue. So, this PR may have needed to be created in OHC.

> My guess is that this might be caused by some thing file not having a thing-type specified eg thing-type id=“"

Here are the file names under /ESH-INF/thing/ that do not have 'thing-type id=' in them...
```
# grep -r -L "thing-type id=" *
channels.xml
controller_serial.xml
```

**Comment by mhilbush** [comment] 2019-10-16 16:41
I'l install the latest binding on build 1690, which should predate the core with the above-reference PR.

Give me a few minutes.

**Comment by cdjackson** [comment] 2019-10-16 16:43
Thanks Scott - that looks fine - those two files are ok.

Thanks for testing this Mark.

**Comment by mhilbush** [comment] 2019-10-16 16:47
Build 1690 has a core dated `133 │ Active │  80 │ 2.5.0.201909150302    │ org.openhab.core`

After installing `245 │ Active │  80 │ 2.5.0.201910150544    │ org.openhab.binding.zwave`, I'm getting the exception.

```
2019-10-16 12:43:59.839 [ERROR] [ig.xml.osgi.XmlDocumentBundleTracker] - Could not send adding finished event for the module 'org.openhab.binding.zwave'!
java.lang.IllegalArgumentException: UID must have at least 2 segments.
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:70) ~[133:org.openhab.core:2.5.0.201909150302]
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:49) ~[133:org.openhab.core:2.5.0.201909150302]
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:48) ~[?:?]
	at org.eclipse.smarthome.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:40) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ChannelXmlResult.toChannelDefinition(ChannelXmlResult.java:135) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toChannelDefinitions(ThingTypeXmlResult.java:94) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.getBuilder(ThingTypeXmlResult.java:145) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toThingType(ThingTypeXmlResult.java:153) ~[?:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlProvider.addingFinished(ThingTypeXmlProvider.java:148) ~[?:?]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.addingFinished(XmlDocumentBundleTracker.java:265) [142:org.openhab.core.config.xml:2.5.0.201909150319]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.parseDocuments(XmlDocumentBundleTracker.java:424) [142:org.openhab.core.config.xml:2.5.0.201909150319]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.processBundle(XmlDocumentBundleTracker.java:398) [142:org.openhab.core.config.xml:2.5.0.201909150319]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.access$6(XmlDocumentBundleTracker.java:393) [142:org.openhab.core.config.xml:2.5.0.201909150319]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$2.run(XmlDocumentBundleTracker.java:363) [142:org.openhab.core.config.xml:2.5.0.201909150319]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by openhab-5iver** [comment] 2019-10-16 16:50
I should be able to write a Jython script to determine the xml that causing the exception. But what else could it be?

**Comment by wborn** [comment] 2019-10-16 16:58
It's this [channel](https://github.com/openhab/org.openhab.binding.zwave/blob/dc0b3b620f50a91603c5454290dfbd771909bac4/src/main/resources/ESH-INF/thing/zwaveme/zuno_1_0.xml#L22-L27) that is missing an `id` and `typeId`.

**Comment by mhilbush** [comment] 2019-10-16 17:01
I guess this was the giveaway... 😉 
```
	at org.eclipse.smarthome.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:40) ~[?:?]
```

**Comment by wborn** [comment] 2019-10-16 17:08
I enriched the exception thrown by the [ThingTypeXmlProvider](https://github.com/openhab/openhab-core/blob/64ae35a0a354a282b6f50f99da44c2d8bfd38de2/bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlProvider.java#L145-L148) with some reflection:

```java
        // create thing and bridge types
        for (ThingTypeXmlResult type : this.thingTypeRefs) {
            try {
                this.thingTypeProvider.add(this.bundle, type.toThingType());
            } catch (Exception e) {
                throw new RuntimeException("Failed to add: " + ToStringBuilder.reflectionToString(type), e);
            }
        }
```

Recompiled the bundle and loaded it into my openHAB instance.

Which gave me all details of the culprit:

`18:54:56.304 [ERROR] [fig.xml.osgi.XmlDocumentBundleTracker] - Could not send adding finished event for the module 'org.openhab.binding.zwave'!
java.lang.RuntimeException: Failed to add: org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult@425d2e69[thingTypeUID=zwave:zwaveme_zuno_01_000,supportedBridgeTypeUIDs=<null>,label=ZUNO1S1D1AI1DI ZUNO1S1D1AI1DI,description=ZUNO1S1D1AI1DI<br /><h1>Overview</h1><p>Zuno with following Configuration</p> <p>1.) Binary Switch</p> <p>2.) Dimmer</p> <p>3.) Temperatur</p> <p>4.) Door open/close Contact</p> <br /><h2>Inclusion Information</h2><p>Push 3 times</p> <br /><h2>Exclusion Information</h2><p>Push 3 times</p> <br /><h2>Wakeup Information</h2><p>Push 1 time</p>,category=<null>,listed=false,extensibleChannelTypeIds=[],representationProperty=<null>,channelTypeReferences=[ChannelTypeXmlResult [id=switch_binary, typeId=switch_binary, properties=[NodeValue [nodeName=property, value=COMMAND_CLASS_SWITCH_BINARY,COMMAND_CLASS_BASIC]]], ChannelTypeXmlResult [id=, typeId=, properties=[NodeValue [nodeName=property, value=COMMAND_CLASS_SENSOR_MULTILEVEL]]], ChannelTypeXmlResult [id=temperature, typeId=temperature, properties=[NodeValue [nodeName=property, value=COMMAND_CLASS_SENSOR_MULTILEVEL]]], ChannelTypeXmlResult [id=switch_dimmer1, typeId=switch_dimmer, properties=[NodeValue [nodeName=property, value=COMMAND_CLASS_SENSOR_MULTILEVEL:1]]], ChannelTypeXmlResult [id=switch_dimmer2, typeId=switch_dimmer, properties=[NodeValue [nodeName=property, value=COMMAND_CLASS_SENSOR_BINARY:2]]], ChannelTypeXmlResult [id=temperature3, typeId=temperature, properties=[]], ChannelTypeXmlResult [id=switch_binary4, typeId=switch_binary, properties=[NodeValue [nodeName=property, value=COMMAND_CLASS_SWITCH_BINARY:4,COMMAND_CLASS_BASIC:4]]]],channelGroupTypeReferences=<null>,properties=[NodeValue [nodeName=property, value=Z-Wave.Me], NodeValue [nodeName=property, value=ZUNO1S1D1AI1DI], NodeValue [nodeName=property, value=0115], NodeValue [nodeName=property, value=0000:0000], NodeValue [nodeName=property, value=1.0], NodeValue [nodeName=property, value=494]],configDescriptionURI=thing-type:zwave:zwaveme_zuno_01_000,configDescription=ConfigDescription [uri=thing-type:zwave:zwaveme_zuno_01_000, parameters=[ConfigDescriptionParameter [name=node_id, type=INTEGER, min=1, max=232, readOnly=true, required=true, verify=false, multiple=false, multipleLimit=null, label=Node ID]], groups=[]]]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlProvider.addingFinished(ThingTypeXmlProvider.java:151) ~[?:?]`

Then I checked the XML for some errors... removed the channel. Replaced the binding with the recompiled version and it properly loaded. :-)

**Comment by cdjackson** [comment] 2019-10-16 17:10
Ah - interesting - I was in the process of adding more logging as well.

Are you going to add this to the core? :)

Anyway.- thanks :)

**Comment by wborn** [comment] 2019-10-16 17:32
Catching the exception and logging the channel/channel-group or thing type UID in that method might be very helpful to troubleshoot these issues in the future.

If the error is in a thing type, like it was in this case, it might also catch the exception and continue adding the other types so the binding continues to work except for Things of that particular type. That way these issues have a smaller impact.

Another approach could be to also validate the XML in SAT. So these issues won't enter the code base and hit users. But it might have quite an impact on build times.

**Comment by wborn** [comment] 2019-10-16 19:57
I've created https://github.com/openhab/openhab-core/pull/1136 which should improve this. :-)

**Comment by cdjackson** [comment] 2019-10-16 20:05
Brilliant - thanks @wborn

**Comment by cdjackson** [comment] 2020-01-04 13:39
Closing this as I recall we found the offender.

**Closed by cdjackson** 2020-01-04 13:39 UTC
